/*
 *
 * ORDER_DETAILS constants
 *
 */

export const orderDetailsConstants = {
  TEST_ORDER_DETAILS_REQUEST: "TEST_ORDER_DETAILS_REQUEST",
  TEST_ORDER_DETAILS_SUCCESS: "TEST_ORDER_DETAILS_SUCCESS",
  TEST_ORDER_DETAILS_FAILURE: "TEST_ORDER_DETAILS_FAILURE",
};
