/*
 *
 * CATEGORIES constants
 *
 */

export const categoriesConstants = {
  TEST_CATEGORIES_REQUEST: "TEST_CATEGORIES_REQUEST",
  TEST_CATEGORIES_SUCCESS: "TEST_CATEGORIES_SUCCESS",
  TEST_CATEGORIES_FAILURE: "TEST_CATEGORIES_FAILURE",
};
