/*
 *
 * PRODUCTS constants
 *
 */

export const productsConstants = {
  TEST_PRODUCTS_REQUEST: "TEST_PRODUCTS_REQUEST",
  TEST_PRODUCTS_SUCCESS: "TEST_PRODUCTS_SUCCESS",
  TEST_PRODUCTS_FAILURE: "TEST_PRODUCTS_FAILURE",
};
